runtime: python39
#env: flex
#instance_class: F2
service: default
handlers:
  - url: /
    static_files: dist/vex/browser/index.html
    upload: dist/vex/browser/index.html
  - url: /
    static_dir: dist/vex/browser
  #- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico)(|\.map))$
  #  static_files: dist/vex/browser/index.html
  #  require_matching_file: false
  #  upload: dist/vex/browser/(.*)(|\.map)
  #- url: /(.*)
  #  static_files: dist/vex/browser/index.html
  #  require_matching_file: false
  #  upload: dist/vex/browser/index.html
